# Generated by Django 2.1 on 2018-05-23 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180523_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_zhanghao',
            new_name='email',
        ),
    ]
